SSHPublicKey = "/ICMDurable/keys/insecure-ssh2.pub"
Region = "us-east-1"
Zone = "us-east-1a,us-east-1b"
Credentials = "/ICMDurable/credentials.ADFS-PowerUsers"
MachineName = "asamary-IRISSpeedTest"
OutputFile = "/ICMDurable/State/asamary-IRISSpeedTest/terraform.out"
