#!/bin/bash

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

source ./buildtools.sh

# funtion build_java_project will add a line with the full image name of each image built
# But we need to start with an empty file:
rm -f ./images_built

build_java_project "image-master"

build_java_project "image-ingest-worker"

build_java_project "image-query-worker"

UI_IMAGE_NAME=intersystemsdc/irisdemo-demo-htap:ui-${DOCKER_TAG}
docker build -t $UI_IMAGE_NAME ./image-ui
echo $UI_IMAGE_NAME >> ./images_built
# This last image was not built with the function build_java_project(). So we will
# add the full image name ourselves:

#The push script will loop on the lines of ./images_build and push them!